telemetry_mode: "v2-stats-nullvm"
conn:
    - 2
    - 4
    - 8
    - 16
    - 32
qps:
    - 100
duration: 100
perf: true
jitter: true
headers: "x-ext-authz:allow"
extra_labels: "use-ext-authz"
load_gen_type: "fortio"
