telemetry_mode: "v2-stats-nullvm"
conn:
    - 64
qps:
    - 100
    - 200
    - 300
    - 400
    - 500
duration: 100
perf: true
jitter: true
headers: "x-ext-authz:allow"
extra_labels: "use-ext-authz"
load_gen_type: "fortio"
